### ISSUE TITLE
[Feature] All settings in Freeplay/Practice

### ISSUE THREAD

**Issue by heavyutils** [g0aty/SickoMenu#45] opened 2024-05-11 05:35 UTC
An option in the menu to have ALL the hosting settings carry over to freeplay/practice, such as Emergency Meetings and Crewmate and Impostor Vision.

Only voting time and speed does for now afaik.

**Comment by g0aty** [comment] 2024-05-11 07:21
Editing the host settings while in game is a planned feature!

**Comment by g0aty** [comment] 2024-06-13 01:32
Duplicate of #22, so this will be closed. However, the feature is planned!

**Closed by g0aty** 2024-06-13 01:32 UTC
Labels: duplicate, enhancement
