### ISSUE TITLE
New Amongus version does NOT work

### ISSUE THREAD

**Issue by Stektax** [g0aty/SickoMenu#73] opened 2024-06-19 15:01 UTC
New Version 18.6.2024 does not work with the menu :) would be great if you update it in the next release :)

If ur working on it rn how is development going btw ?

Thank you for this amazing project

**Comment by heavyutils** [comment] 2024-06-19 15:06
No comment from developer, but we estimate 3-5 days for a hotfix and 3-6 weeks for the full release.

**Comment by HasanTheGlitcher** [comment] 2024-06-19 16:58
@heavyutils What's Up?

Are you excited for the hotfix? if so, then im too.

**Comment by RobloxGabriel1** [comment] 2024-06-19 17:16
in discord, the developer said that he would be fixing it as soon as possible.

**Comment by heavyutils** [comment] 2024-06-19 17:18
> @heavyutils What's Up?
> 
> 
> 
> Are you excited for the hotfix? if so, then im too.

Ofc dude also I don't want to be banned on my main among us acc and this mod fixes it :)
So I'm not gonna play among us much until it gets fixed. It's bad without the mod. The name hacks and free chat hacks R the best.
The hotfix from what I guess will just be making it work, and making the new roles selectable. I think nothing else will come just immediately.

**Comment by g0aty** [comment] 2024-06-20 00:35
Duplicate of #68

**Closed** 2024-06-20 00:35 UTC

**Comment by RobloxGabriel1** [comment] 2024-06-20 22:57
Replying to @heavyutils: same im not gonna play among us alot until they patch it.
