### ISSUE TITLE
update to 2024.6.18

### ISSUE THREAD

**Issue by Night-GUA** [g0aty/SickoMenu#77] opened 2024-06-21 16:15 UTC
update to 2024.6.18,pls

**Comment by vofq** [comment] 2024-06-21 17:52
damn ur smart for figuring this out ngl, you should join the discord and tell the others :D idk if anyone else knows yet

**Comment by WayloFunk** [comment] 2024-06-22 01:58
duplicate of #68

**Comment by RakkunSatura** [comment] 2024-06-22 05:13
Amigo eres inteligente por favor saca la nueva versión 😔

**Closed** 2024-06-22 14:48 UTC
