### ISSUE TITLE
Menu doesn't work after update

### ISSUE THREAD

**Issue by KidTechnical** [g0aty/SickoMenu#69] opened 2024-06-18 17:55 UTC
Self-explanatory. The game crashes whenever I inject the DLL.

**Comment by heavyutils** [comment] 2024-06-18 18:25
For me it just doesn't load it

**Comment by HasanTheGlitcher** [comment] 2024-06-19 08:16
same

**Comment by WayloFunk** [comment] 2024-06-19 15:48
Duplicate of #68

**Comment by g0aty** [comment] 2024-06-20 00:33
Duplicate of #68

**Closed** 2024-06-20 00:33 UTC
